"""Added year_built column to hotels table

Revision ID: cded0641db6a
Revises: 59bc482778e0
Create Date: 2023-06-14 15:54:19.753790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cded0641db6a'
down_revision = '59bc482778e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_built', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('year_built')

    # ### end Alembic commands ###
